In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.version.__version__)

2.1.0+cu118


## Introduction to Tensors
###Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8, 11],
                      [9, 10, 12]])
MATRIX

tensor([[ 7,  8, 11],
        [ 9, 10, 12]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 3])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0][0]

tensor([1, 2, 3])

In [ ]:
TENSOR2 = torch.tensor([ [[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]
                          ],
                         [[11, 12, 13],
                          [14, 15, 16],
                          [17, 18, 19]
                          ]])
print(TENSOR2)
print(TENSOR2.ndim)
print(TENSOR2.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])
3
torch.Size([2, 3, 3])


### Random Tensors
why random tensors? They are important since the way many NNs work is that they start with tensors full of random numbers and then adjust the random numbers to better represen that data.

`Start with randoom numbers -> look at data -> update random numbers -> lool at data -> update random numbers`

In [ ]:
# create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0944, 0.9430, 0.7980, 0.5637],
        [0.3378, 0.3204, 0.3313, 0.8388],
        [0.7258, 0.7506, 0.7015, 0.6055]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_tensor2 = torch.rand(5, 5, 4)
random_tensor2

tensor([[[0.0563, 0.9562, 0.3710, 0.7614],
         [0.6324, 0.3738, 0.6623, 0.1727],
         [0.3360, 0.0149, 0.4230, 0.5538],
         [0.0894, 0.5732, 0.1021, 0.0448],
         [0.3744, 0.0418, 0.7206, 0.1911]],

        [[0.2399, 0.2568, 0.6722, 0.7924],
         [0.4264, 0.9528, 0.4917, 0.7085],
         [0.9894, 0.1915, 0.6625, 0.4554],
         [0.3382, 0.4849, 0.8420, 0.9665],
         [0.3567, 0.3028, 0.9222, 0.7259]],

        [[0.9492, 0.1187, 0.3079, 0.5154],
         [0.1056, 0.6161, 0.5033, 0.2262],
         [0.9869, 0.7359, 0.5662, 0.6549],
         [0.6437, 0.1623, 0.0465, 0.2908],
         [0.9952, 0.9727, 0.9644, 0.6817]],

        [[0.8521, 0.6970, 0.7702, 0.0560],
         [0.9136, 0.9182, 0.6754, 0.2056],
         [0.0346, 0.2763, 0.4018, 0.9690],
         [0.4409, 0.4173, 0.3203, 0.2407],
         [0.9976, 0.5122, 0.3777, 0.7281]],

        [[0.0146, 0.2718, 0.3948, 0.8268],
         [0.6181, 0.5756, 0.7945, 0.1163],
         [0.8070, 0.9413, 0.2645, 0.2057],
   

### Zeros and ones

In [ ]:
# create a tensor of all zeroes
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [ ]:
# use torch.range
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
*Note:* Tensor datatypes is one of the 3 big issues you face in deep lerning with pytorch:
1. Tensors not right datatype
2. Tensors not the right shape
3. Tensors not on the right device

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None,# could be torch.float16
                               device=None, # could be cpu, cuda
                               requires_grad=False#whether or not to track gradients with this tensor operation
                               )
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right stape - to do get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to do get device from a tensor, can use `tensor.device`

In [ ]:
 # create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6306, 0.4259, 0.6513, 0.7877],
        [0.2024, 0.0371, 0.9258, 0.9359],
        [0.2494, 0.7418, 0.1145, 0.3217]])

In [ ]:
# Find out details about some tensor
print(f"the datatype of tensor: {some_tensor.dtype}")
print(f"the shape of tensor: {some_tensor.shape}")
print(f"the size of tensor: {some_tensor.size()}")
print(f"the device of tensor: {some_tensor.device}")

the datatype of tensor: torch.float32
the shape of tensor: torch.Size([3, 4])
the size of tensor: torch.Size([3, 4])
the device of tensor: cpu


In [ ]:
# cuda0 = torch.device('cuda:0')
# some_tensor.to(cuda0, dtype=torch.float16)

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplicaton


In [ ]:
# create a tensor and add 10  to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# subtract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try in built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

 https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
# element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: { tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# matrix_mul
torch.matmul(tensor, tensor)

tensor(14)

### Shape errors

In [ ]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])
tensor_B = torch.tensor([[7, 10],
                          [8, 11],
                          [9, 12]])
torch.mm(tensor_A, tensor_B)# torch.mm is an alias for torch.matmul

RuntimeError: ignored

In [ ]:
# the matrix operation works when B is trannsposed as B.T
# torch.mm(tensor_A, tensor_B.T)
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: tensor_A = {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match')
print('Output: \n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: tensor_A = torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# find the mean torch.mean requires float not long, x is currently long
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [ ]:
# find the positional min
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [ ]:
x[0]

tensor(1)

In [ ]:
# find the positional max
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [ ]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return same tensor with a different shape but keep the same memory of original tensor
* Stacking - combine mulptiple tensors on top of each other(vstack) or beside each other(hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a  `1` dimensions to target tensor
* Permute - return view of the input with dimensions permuted(swapped) in a cxertain way

### Reshape

In [ ]:
# create a tensor
import torch
x = torch.arange(1, 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# add an exra dimension
# reshape has to be compatible wih original shape
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

RuntimeError: ignored

In [ ]:
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
x_reshaped = x.reshape(2, 10)
x_reshaped, x_reshaped.shape

RuntimeError: ignored

In [ ]:
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

RuntimeError: ignored

### Change the view

In [ ]:
# change the vew
x_view = torch.arange(1, 10.)
x_view

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
z = x_view.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x_view since the view of a tensor shares the same memory as the original input
z[:, 0] = 5
z, x_view

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

### Stack tensors on top of each other

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=2)
x_stacked

IndexError: ignored

### Squeeze and unsqueeze

In [ ]:
print(f'Previous tensor: {x_reshaped}')
print(f'Previous tensor: {x_reshaped}')

# remove extra dimensions
x_squeezed = torch.squeeze(x_reshaped)
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
Previous tensor: tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

New tensor: tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([2, 5])


In [ ]:
# unsqueeze adds a single dimension to a target tensor at a specific dim
print(f'Previous target: {x_squeezed}')
print(f'Previous tensor: {x_squeezed.shape}')

# add an extra dimensions
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
Previous tensor: torch.Size([2, 5])

New tensor: tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]])
New shape: torch.Size([1, 2, 5])


In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')


New tensor: tensor([[[ 1.,  2.,  3.,  4.,  5.]],

        [[ 6.,  7.,  8.,  9., 10.]]])
New shape: torch.Size([2, 1, 5])


### Permute

In [ ]:
x_original = torch.rand(224, 224, 3)

# permute the original tensor to rearrange the dim order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0 -> 1, 1 -> 2 and 2 -> 0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}')

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 1
x_permuted[0,0,0]

tensor(1.)

##Indexing (Selecting data from tensors)

In [ ]:
# create a tensor
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# index on middle bracket (dim = 1)
x[0, 0] # x[0][0]

tensor([1, 2, 3])

In [ ]:
# index on the most inner bracket(last dimension(dim))
x[0,0,0]

tensor(1)

In [ ]:
# you can also use : to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1, 1]

tensor([5])

In [ ]:
x[0,0, :]

tensor([1, 2, 3])

In [ ]:
x[0, 2, 2]

tensor(9)

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

## Pytorch and numpy

* Data in numpy, want pytorch sensor -> `torch.from_numpy(ndarray)`
* pytorch tensor -> numpy -> `torch.Tensor.nupy()`

In [ ]:
#  numpy array to tensor
import numpy as np
import torch

array = np.arange(1, 8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor_m = tensor.type(torch.float32)
tensor_m

tensor([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
array += 1
array, tensor, tensor_m

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# tensor to numpy
tensor = torch.ones(7)
np_tensor = tensor.numpy()
tensor, np_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor += 1
np_tensor, tensor

(array([2., 2., 2., 2., 2., 2., 2.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

 ## Reproducability

 To reduce the randomness of NN, we use the random seed

In [2]:
import torch

#create 2 random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0550, 0.5031, 0.8033, 0.1406],
        [0.2886, 0.1771, 0.0510, 0.1055],
        [0.6837, 0.7205, 0.8190, 0.3928]])
tensor([[0.2825, 0.4782, 0.1304, 0.5077],
        [0.1025, 0.1792, 0.7017, 0.7664],
        [0.3402, 0.5483, 0.4742, 0.7848]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [3]:
# l's make random reproducible tensors

# set reandom seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch objects on GPUs

In [1]:
!nvidia-smi

Sun Dec  3 21:30:54 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
# check for GPU access
import torch
torch.cuda.is_available()

True

In [5]:
# set up device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [4]:
# count GPU
torch.cuda.device_count()

1

### Putting tensors(and models) on the GPU

In [6]:
# create a tensor (defgault on the CPU)
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Move tensor back to CPU


In [8]:
tensor_on_gpu.numpy()

TypeError: ignored

In [11]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises